### ISSUE TITLE
add contributor

### ISSUE THREAD

**Issue by aaorella** [g1AI/SAI_PYMES#1]
@all-contributors please add @aaorella  for code

**Comment by aaorella** [comment]
@all-contributors please add @aaorella for code

**Comment by g1AI** [comment]
@all-contributors please add @Komodroid  for code

**Comment by g1AI** [comment]
@all-contributors please add @jxvargas for code
@all-contributors please add @asuskffor code
@all-contributors please add @eeiycode

**Comment by g1AI** [comment]
@all-contributors please add @jxvargas for code

**Comment by g1AI** [comment]
@all-contributors please add @asuskffor code

**Comment by g1AI** [comment]
@all-contributors please add @eeiy for code

**Comment by g1AI** [comment]
@all-contributors please add @asuskf for code

**Comment by g1AI** [comment]
@all-contributors please add @eeiy for code
@all-contributors please add @jxvargas for code
@all-contributors please add @Komodroid for code

**Comment by g1AI** [comment]
@all-contributors please add @eeiy for code
